### PR TITLE
Kieker 1987 update

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Update dependencies and remove unused dependencies in the aspectj probe gradle

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Comment by DaGeRe** [comment]
Gradle update was missing; was performed using `for file in $(find . -name "gradle-wrapper.properties"); do sed -i "s/gradle-8.6-bin/gradle-8.8-bin/" $file; done`.

**Review by shinhyungyang — APPROVED** [review]
Thank you for the contribution. It looks good to me.

**Comment by DaGeRe** [comment]
We got this problem on Jenkins here as well:

```
java.lang.IllegalStateException: Can't add different class with same name: _BuildScript_
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:100)
	at PluginClassLoader for asm-api//org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:395)
	at PluginClassLoader for jacoco//org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
	at PluginClassLoader for asm-api//org.objectweb.asm.ClassReader.accept(ClassReader.java:749)
	at PluginClassLoader for asm-api//org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:117)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
Caused: java.io.IOException: Error while analyzing /var/lib/jenkins/jobs/kieker-dev/branches/PR-587/builds/11/jacoco/classes/cp_proj/_BuildScript_.class with JaCoCo 0.8.11.202310140853/f33756c.
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:163)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:135)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:158)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:195)
	at PluginClassLoader for jacoco//org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:228)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.ExecutionFileLoader.analyzeStructure(ExecutionFileLoader.java:127)
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 49afc14e-ba6b-4810-ba05-0ff04d2bec2d
Caused: java.io.IOException: While reading class directory: /var/lib/jenkins/jobs/kieker-dev/branches/PR-587/builds/11/jacoco/classes
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.ExecutionFileLoader.analyzeStructure(ExecutionFileLoader.java:130)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.ExecutionFileLoader.loadBundleCoverage(ExecutionFileLoader.java:138)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.JacocoReportDir.parse(JacocoReportDir.java:110)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.JacocoBuildAction.loadRatios(JacocoBuildAction.java:331)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.JacocoBuildAction.load(JacocoBuildAction.java:321)
	at PluginClassLoader for jacoco//hudson.plugins.jacoco.JacocoPublisher.perform(JacocoPublisher.java:678)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I'll check whether a gradle update to 8.9 can fix this.

**Comment by DaGeRe** [comment]
This is hopefully superseded https://github.com/kieker-monitoring/kieker/pull/612.

**Comment by DaGeRe** [comment]
As planned, this is no longer needed. I close the PR and delete the branch.

**Pull request closed without merging**
