### PR TITLE
Jenkins testing

### PR DESCRIPTION
**Pull request by rju**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Adjusted the build to the new build server
- Due to disc space limitations, deactivate the production of zip and tgz result archives.

## Code Quality Thresholds
- Code was not changed

### CODE REVIEW

**Comment by rju** [comment]
Additional note. The labels for the docker containers should not be specified in the Jenkinsfile, as this can be done in the Jenkins configuration. Thus, the build can be moved to a different node at any time without changing the Jenkinsfile again.

**Comment by duelle** [comment]
Is there a specific reason why the BinarySerializer tests are set to be ignored?
https://github.com/kieker-monitoring/kieker/pull/251/commits/aa3ce59d1573c8c836106a85d4eb2aaac80b6840
https://github.com/kieker-monitoring/kieker/pull/251/commits/4af20c354cffafadff94f5112ae458d02dd83a75
As you mention "for now" in the commit message I was not sure whether this should be changed back before the merge.

**Comment by avanhoorn** [comment]
> Is there a specific reason why the BinarySerializer tests are set to be ignored?
> [aa3ce59](https://github.com/kieker-monitoring/kieker/commit/aa3ce59d1573c8c836106a85d4eb2aaac80b6840)
> [4af20c3](https://github.com/kieker-monitoring/kieker/commit/4af20c354cffafadff94f5112ae458d02dd83a75)
> As you mention "for now" in the commit message I was not sure whether this should be changed back before the merge.

Yes, I had the same question for the archives.

**Comment by rju** [comment]
Both tests failed randomly. While working in the branch, they did not in the PR-251. I suspect that this is some sort of race condition, as no code changes where made anywhere. Changes in the build scripts only deactivated the tgz deliverables due to size restrictions (which we can take back when the archive gets smaller again due to an update in the build system). Thus, I temporarily deactivated the two tests to get the necessary Jenkinsfile changes into Kieker (which we need to be able to fix all the other related issues).

While deeper inspecting the test. It is highly suspicious. (a) it claims to test the BinarySerializer, but the serializer are in the project kieker-common. So wrong package. It is also not testing the BinarySerializer, but instead the use of it in context of the ChunkingCollector. However, I did not want to remove the code or just comment the test out (which would be also an option), but instead set two ignore tags which cause additional errors with Checkstyle forcing us to not forget the issue.

**Comment by avanhoorn** [comment]
> Changes in the build scripts only deactivated the tgz deliverables due to size restrictions (which we can take back when the archive gets smaller again due to an update in the build system).

OK, I see. From your initial comment "production of zip and tgz result archives." I understood that you deactivated both ZIP and TGZ. In general, I think we could get rid of the TGZs.

**Comment by rju** [comment]
Currently, we have severe disc space issues. Thus I cannot get anything built. Technicians willl fix this by end of the week.

**Comment by rju** [comment]
Currently, we have severe disc space issues. Thus I cannot get anything built. Technicians will fix this by end of the week. Currently, a completed build locally requires 4.4 GB. The failing builds on Jenkins have 2.4 GB. The build-node3 has 10 GB disc space in total. However, it seems large portions are allocated by the system outside of the docker container.

**Comment by rju** [comment]
So finally, it compiles. I reactivated the test (deactivated some commits earlier) also reactivated generating tarball. We can discuss at a later date whether they should be removed. Only changes now are to the Jenkinsfile, some formatting changes and the increase of allowed Checkstyle errors. I would like to keep this for now (and not change it back), as more modifications will happen to the whole built system which will increase and decrease errors. Thus, I would rather adjust them at the end of these changes.

**Pull request merged**
