### PR TITLE
Skip Tests on Windows to Avoid Github Actions Failures

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Add `OSUtil` that tells whether the current build is on windows. I added it as a general util in the `kieker` package, like `Await`.
- Contribution 2 Add `Assume.assumeFalse` to failing tests, so they are not executed on windows builds.

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Comment by rju** [comment]
I took the liberty to fix some checkstyle and pmd issues. Before creating an PR, it helps to run ./gradlew -x test check to check whether all code issues are fixed.

**Review by rju — APPROVED** [review]
Looks good, after minor fixes.

**Comment by DaGeRe** [comment]
Thanks for the code issue fixes!

From my point of view, this could be merged, or is there anything missing?

**Comment by rju** [comment]
I was waiting for Jenkins to complete its magic.

**Pull request merged**
