### PR TITLE
Make Take and PutStrategy configurable

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

Currently, Kieker relies on a BlockingQueue, and if the used queue is not blocking, it is decorated to be blocking. This is done using `SCBlockingTakeStrategy` / `SPBlockingPutStrategy`. Especially for small workloads, `LockSupport.unpark` may cause much CPU consumption. Kieker additionally contains a `YieldPutStrategy` and `YieldTakeStrategy`, but as far as I see, there is no option to use them. 

For my use case, I would like to specify queue, put strategy and take strategy in the `kieker.monitoring.properties` like this:

```
kieker.monitoring.core.controller.WriterController.RecordQueueFQN=org.apache.commons.collections4.queue.CircularFifoQueue
kieker.monitoring.core.controller.WriterController.QueuePutStrategy=kieker.monitoring.queue.putstrategy.YieldPutStrategy
kieker.monitoring.core.controller.WriterController.QueueTakeStrategy=kieker.monitoring.queue.takestrategy.YieldTakeStrategy
```
Therefore, I added the option to make it configurable.

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Add configurability for PutStrategy and TakeStrategy

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Comment by rju** [comment]
I had a look at the contribution. It should be fine. However, there are a few code style issues you must fix before we can add the code.
The following values must be declared final in WriterController
203         Class<?> strategyClass = Class.forName(strategyName);
215        Class<?> strategyClass = Class.forName(strategyName);

39 and 40 in WriterController refer to unused imports.

Missing whitespace before =.
115  final TakeStrategy takeStrategy= newTakeStrategy(takeStrategyFqn);

You can fix these things all together with setting up Eclipse following the steps in our setup instructions. In case you use some other IDE, you most likely can set the same parameter there. Also please record such setup efforts, as we could add them to our documentation for others.

https://kieker-monitoring.atlassian.net/wiki/spaces/DEV/pages/24215585/Kieker+Coding+Conventions+in+Eclipse

**Comment by rju** [comment]
Unfortunately, there are still issues left:
204 and 217 WriterController: require final modifiers  Checkstyle and PMD recommend this.
210 and 223 WriteController e.printStackTrace(); is discouraged in PMD. Better add the stacktrace to the logger. If it is necessary.

**Comment by rju** [comment]
Here a snippet of the build error:
 Checkstyle:
  Errors: 3 (Threshold: 1)
  Warnings: 4 (Threshold: 4)
  Info: 295

 PMD:
  Errors: 4 (Threshold: 4)
  Warnings: 113 (Threshold: 109)
  Info: 0

**Comment by DaGeRe** [comment]
Thanks for the hint! I hope it's finally fixed now.

**Pull request merged**
