### PR TITLE
Close directory reader stream

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Files.listFiles should be closed, so windows user can access the folder again

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Review by rju — COMMENTED** [review]
Looks good. However, a try block without a catch does that make sense? If yes, I would approve it otherwise just add one with a useful error message.

**Comment by DaGeRe** [comment]
Isn't this a change to an existing try, so there is a catch? Anyway, since the try with resources assures closing of the resource, in my opinion it would also be ok without catch.

**Review by rju — DISMISSED** [review]

**Comment by rju** [comment]
Most of it looks good. However, checkstyle is unsatisfied with the sequence of imports in DirectoryReaderStage.java
In case you use Eclipse, the standard Kieker setup should ensure that the save actions should fix this issue automatically.
If not, the sequence used in cs-conf.xml is "java, javax, junit, org, com, ch, de, kieker, kieker.test"
Thus, the teetime import must be below and there must be a empty line between:
import kieker.common.util.filesystem.FSUtil;

import teetime.stage.basic.AbstractTransformation;

**Review by rju — APPROVED** [review]

**Comment by rju** [comment]
In case the branch is completed, please delete the branch.

**Comment by DaGeRe** [comment]
Thanks for the hint, I deleted it now.

**Pull request merged**
