### PR TITLE
Get CPD working with Gradle properly

### PR DESCRIPTION
**Pull request by aaschmid**
* fixes https://github.com/aaschmid/gradle-cpd-plugin/issues/21

Good things come to those who wait. I eventually fixed your problem and created the pull request to share my fix :-)

### CODE REVIEW

**Comment by aaschmid** [comment]
Please review and give me hints for wanted changes :-)

**Comment by duelle** [comment]
@ChristianWulf As far as I remember you were investigating these issues. Could you have a look please?

**Comment by ChristianWulf** [comment]
Thanks for your PR. However, the report file is generated with an invalid encoding name "Cp1252".
`<?xml version="1.0" encoding="Cp1252"?>
<pmd-cpd> ...`

Quoting from [stackoverflow](https://stackoverflow.com/questions/16141416/is-encoding-cp1252-invalid-in-an-xml-file):
> i guess the encoding you're looking for COULD be windows-1252. Cp1252 might be a valid charset in java, but in XML, you're not supposed to use it (by that name).

Could you please generate the file with a valid encoding name, preferably in UTF-8?

**Comment by aaschmid** [comment]
Hi @ChristianWulf,

You can simple add `encoding = 'UTF-8'` to the reports section. What is the real encoding of the file? Can you check with `file -i <filename>`?

Cheers,
Andreas

**Comment by ChristianWulf** [comment]
Hi @aaschmid ,
works great! Thanks. Moreover, the output file's actual encoding is UTF-8.

**Pull request merged**
