### PR TITLE
Kieker 1696 forbid pr to target to the stable branch

### PR DESCRIPTION
**Pull request by ChristianWulf**

### CODE REVIEW

**Comment by duelle** [comment]
The PR failed once because of the timeout.
See: https://build.se.informatik.uni-kiel.de/jenkins/job/kieker-monitoring/job/kieker/view/change-requests/job/PR-151/1/console

**Comment by ChristianWulf** [comment]
Yes, sure. That's what the timeout is for ;) Currently, fetching from github is buggy. Even on my machine. So, it's not the fault of the timeout or of Jenkins.

**Comment by duelle** [comment]
The question I wanted to raise here is whether we want to fail the build in such cases. With the current setup (all) our builds would fail if there would be comparably small delay. This way we would have to re-issue the builds every time there is such a "buggy" condition.

I expected this timeout to be more aimed at the issue that we had 'hanging' builds that were locking up resources like our worker nodes. So the timeout would rather take care of terminating them after some time to free up the resources again.

**Comment by ChristianWulf** [comment]
So, do you propose to wrap the timeout around the whole pipeline? If not, I didn't get your point. The fetching would hang forever, if we do not interrupt it.

**Pull request merged**
