### PR TITLE
get CPD working with Gradle properly

### PR DESCRIPTION
**Pull request by aaschmid**
* fixes https://github.com/aaschmid/gradle-cpd-plugin/issues/21

Good things come to those who wait. I eventually fixed your problem and created the pull request to share my fix :-)

### CODE REVIEW

**Comment by aaschmid** [comment]
hm ... strange. Works perfectly on my local machine. Which Java version is used on Jenkins?

**Comment by duelle** [comment]
@aaschmid Currently we're using OpenJDK 7 within a Docker container.
The Docker container is `kieker/kieker-build:openjdk7`

**Comment by aaschmid** [comment]
Hm ... the checkout failed ...

**Comment by duelle** [comment]
@aaschmid Thank you for the hint.
The issue with the failing build should be resolved now.
I also just triggered a new pipeline run for this pull request.

**Comment by duelle** [comment]
@aaschmid could you please close this pull request and create a new one against the 'master' branch instead of the 'stable' branch?
Our current strategy is to merge PRs into master which then is built again and then automatically pushed to stable. Unfortunately, we cannot define different branches for PRs and checkouts with GitHub to enforce this. Sorry for the inconvenience and thank you for your contribution!

**Comment by aaschmid** [comment]
Closed this as requested by @duelle. New one is #103 (even if #100 would have been something special ;-)

**Pull request closed without merging**
