### PR TITLE
Zuul support

### PR DESCRIPTION
**Pull request by avanhoorn**
Pull request for https://kieker-monitoring.atlassian.net/browse/KIEKER-1516

### CODE REVIEW

**Comment by duelle** [comment]
Are there files missing? In commit "Added zuul-specific Pre- and Post- interceptors."
 (https://github.com/kieker-monitoring/kieker/pull/48/commits/0734c13dc96bb0e6b0ad6dae021ebb5b27905b48) only libraries have been added to the classpath, but no interceptors have been added. The interceptors before stem from pull request #25.

**Comment by ChristianStier** [comment]
@duelle Thanks for the hint, I will check if I forgot to add the files.

**Comment by ChristianStier** [comment]
Sorry, this kind of fell to the wayside for me. I have just updated my fork and merged my changes. I will keep track of the CI result.

**Comment by duelle** [comment]
As we have a newer PR with the changes (#197), I will close this one.

**Pull request closed without merging**
