### PR TITLE
Check parameter for validity

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Check the parameters that should contain response time units for correct values, otherwise, misunderstandings of typos lead to hard-to-trace errors

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Comment by rju** [comment]
I checked the code and it looks good. However, it is not a good idea to implement validity checks in parameter getters. IT is better to add them either to the checkParameters routine (old style), but not available for the old trace-analysis, or in the Parameter annotation with validateWith = ...
I moved the code accordingly. This also reduces the count of PMD and Checkstyle errors. ;)

**Review by rju — DISMISSED** [review]
Looks good.

**Comment by rju** [comment]
There seems to be still an issue with the release-test of the trace-analysis.

**Comment by DaGeRe** [comment]
Thanks for the adaption. Where do you see the problem with the trace-analysis?

**Comment by rju** [comment]
The release check extended script says:
```
20:02:42.729 [main] ERROR TraceAnalysisToolMain - Parameter --plot-Deployment-Component-Dependency-Graph requires on of the following decorators: responseTimes-ns, -us, -ms or -s
Usage: <main class> [options]
  Options:
    --addDescriptions
      Adds descriptions to elements according to the given file as a 
      properties file (key: component ID, e.g., @1; value: description)
    --buffer-size
      Size of the read buffer, default is 8192 bytes
    -d, --debug
      prints additional debug information
      Default: false
    --filter-traces
      Consider only the traces not identified by the list of trace IDs. 
      Defaults to no traces.
    -h, --help
      prints the usage information for the tool, including available options
    --ignore-assumed-calls
      If selected, assumed calls are visualized just as regular calls.
      Default: false
    --ignore-executions-after-date
      Executions ending after this date (UTC timezone) or monitoring timestamp 
       are ignored.
    --ignore-executions-before-date
      Executions starting before this date (UTC timezone) or monitoring 
      timestamp are ignored.
    --ignore-invalid-traces
      If selected, the execution aborts on the occurence of an invalid trace.
      Default: false
    --include-self-loops
      If selected, self-loops are included in the visualizations.
      Default: false
    -i, --inputdirs
      Log directories to read data from
    --max-trace-duration
      Threshold (in ms) after which incomplete traces become invalid. Defaults 
      to 600,000 (i.e, 10 minutes).
    -p, --output-filename-prefix
      Prefix for output filenames
  * -o, --outputdir
      Directory for the generated file(s)
    --plot-Aggregated-Assembly-Call-Tree
      Generate and store an aggregated assembly-level call tree (.dot)
      Default: false
    --plot-Aggregated-Deployment-Call-Tree
      Generate and store an aggregated deployment-level call tree (.dot)
      Default: false
    --plot-Assembly-Component-Dependency-Graph
      Generate and store an assembly-level component dependency graph (.dot)
    --plot-Assembly-Operation-Dependency-Graph
      Generate and store an assembly-level operation dependency graph (.dot)
    --plot-Assembly-Sequence-Diagrams
      Generate and store assembly-level sequence diagrams (.pic)
      Default: false
    --plot-Call-Trees
      Generate and store call trees for the selected traces (.dot)
      Default: false
    --plot-Container-Dependency-Graph
      Generate and store a container dependency graph (.dot file)
      Default: false
    --plot-Deployment-Component-Dependency-Graph
      Generate and store a deployment-level component dependency graph (.dot)
    --plot-Deployment-Operation-Dependency-Graph
      Generate and store a deployment-level operation dependency graph (.dot)
    --plot-Deployment-Sequence-Diagrams
      Generate and store deployment-level sequence diagrams (.pic)
      Default: false
    --print-Assembly-Equivalence-Classes
      Output an overview about the assembly-level trace equivalence classes
      Default: false
    --print-Deployment-Equivalence-Classes
      Output an overview about the deployment-level trace equivalence classes
      Default: false
    --print-Execution-Traces
      Save execution trace representations of valid traces (.txt)
      Default: false
    --print-Message-Traces
      Save message trace representations of valid traces (.txt)
      Default: false
    --print-System-Model
      Save a representation of the internal system model (.html)
      Default: false
    --print-invalid-Execution-Traces
      Save a execution trace representations of invalid trace artifacts (.txt)
      Default: false
    --repair-event-based-traces
      If selected, BeforeEvents with missing AfterEvents e.g. because of 
      software crash will be repaired.
      Default: false
    --select-traces
      Consider only the traces identified by the list of trace IDs. Defaults 
      to all traces.
    --short-labels
      If selected, abbreviated labels (e.g., package names) are used in the 
      visualizations. 
      Default: false
    --traceColoring
      Color traces according to the given color map given as a properties file 
      (key: trace ID, value: color in hex format, e.g., 0xff0000 for red; use 
      trace ID 'default' to specify the default color)
    -v, --verbose
      verbosely prints additional information
      Default: false
```

It seems that the new checker you added is more strict than before (before you got strange warnings).
It looks like parameter setups in the check script has to be changed.
I'll test this and let you know.

**Comment by DaGeRe** [comment]
Thanks for the correction. To improve understandability of the error message, I'd recommend to also print the wrong parameter inside the error.

**Comment by rju** [comment]
We have an issue with Jenkins due to a plugin upgrade. Role back is unfortunately not possible. The issue was also flagged by others. So this is a shitty situation, but maybe it will be fixed soonish.

**Comment by rju** [comment]
Jenkins is available again.

**Pull request merged**
