### PR TITLE
Enable Github Actions Build

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request

As discussed in the meeting and described in issue https://kieker-monitoring.atlassian.net/browse/KIEKER-1868 a Github actions build which executes the unit tests on Java 8, 11 and 15 and latest ubuntu and windows is added.

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Github actions script for execution

### CODE REVIEW

**Comment by DaGeRe** [comment]
One problem that arises on actions with PRs is that results can not be published since PR authors often do not have the rights to access the repository (https://github.com/actions/first-interaction/issues/10). While the tests run as usual, publishing the test results is not possible. 

From my point of view, the easiest solution would be to use two workflows:
- A workflow for regular runs which publish test results and
- A second workflow for PR-runs, which do not publish test results (and for them, you'd need to manually inspect the logs)

While this is not a very nice solution, I currently see no better option.

**Review by duelle — COMMENTED** [review]
Would it be easily possible to also add macOS to the execution environments? That could be helpful as more and more people and companies use Mac for software development.

**Comment by DaGeRe** [comment]
Yes, I just added it to the workflow-files, and it seems like the runs are started correctly.

**Review by duelle — DISMISSED** [review]
Thanks for adding macOS. In the name/label (line 22) in each of the files, Java 1.8 is explicitly mentioned. As we test multiple versions of java, we could just remove the explicit version, right?
Apart from that, the PR looks good to me.

**Comment by DaGeRe** [comment]
Thanks for the hint, you are right, the current Java version should be referenced there. I added a commit changing this.

**Review by duelle — APPROVED** [review]
Thanks!
From my point of view, this can be merged now.

**Comment by rju** [comment]
We accept this contribution. Despite the lack of successful builds on github. These must be addressed separately

**Pull request merged**
