### PR TITLE
Kieker 1996 update to gradle8 9

### PR DESCRIPTION
**Pull request by shinhyungyang**
# Pull Request

## Contribution
This pull request provides the following contribution to Kieker
- Upgrade to Gradle 8.9
- Explicated Jacoco coverage pattern for classes in Jenkinsfile

### CODE REVIEW

**Comment by rju** [comment]
We seem to have an issue with merging this branch and main. Some issues are in Java files that do not follow the code style of Kieker.

**Comment by rju** [comment]
Usually this should not lead to a merge conflict. Also the merge conflict of the binary files is new. I do not know why we get this.

**Comment by shinhyungyang** [comment]
@rju Thank you for having a look. The merge is mostly about gradle script/binary updates. I can disard this pull request and prepare a new one from the current main. Does this make sense to you?

**Comment by DaGeRe** [comment]
Doing this all over again is one option, the probably easier option is manually rebasing. 

So first, I pulled the newest commits of `main` and `KIEKER-1996-UpdateToGradle8-9`, checked out `KIEKER-1996-UpdateToGradle8-9`, and did `git rebase main`. Now, the merge conflicts occured.

To fix them, for every conflict, we need to checkout the branch version, for example `git checkout KIEKER-1996-UpdateToGradle8-9 -- examples/JavaEEServletContainerExample/gradle/wrapper/gradle-wrapper.jar` 

To do this with every changed file, I did `git status | grep "von beiden geändert" | awk -F':' '{print $2}' | xargs git checkout KIEKER-1996-UpdateToGradle8-9 -- $1` (parsing the German git output - so please set your OS to German for this one ;-) ). 

Now, I pushed to this branch with `--force`, and it builds again. If this is successful, we can merge.

And I wouldn't expect errors in Java files `git diff main --name-only | grep java` is empty...

**Comment by shinhyungyang** [comment]
@DaGeRe Thank you for the nice description and your expertise in revision controls. I will wait until all the builds are finished and return to PR.

**Review by DaGeRe — APPROVED** [review]
Looks all good, can be merged from my point of view.

**Comment by shinhyungyang** [comment]
Thank you!

**Pull request merged**
