### PR TITLE
1.15.2 back to master

### PR DESCRIPTION
**Pull request by DaGeRe**
# Pull Request
This is a merge back to master as described in https://kieker-monitoring.atlassian.net/wiki/spaces/DEV/pages/5865680/Release+Creation.

## Contribution
This pull request provides the following contribution to Kieker
- Contribution 1 Merge back to master
- Contribution 2

## Code Quality Thresholds
- [ ] It was necessary to raise any code quality thresholds
- If yes, which had to be raised and why was it necessary?
..

### CODE REVIEW

**Comment by DaGeRe** [comment]
I've now tried to resolve the conflicts (and hope that I did not mistakenly chose old commit parts), but there are some final problems:
- We seem to have security issues in our master branch: https://github.com/kieker-monitoring/kieker/security/dependabot We should fix this in the future.
- When building, I get an exception:

```
> Task :aspectJJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aspectJJar'.
> Entry META-INF/maven/org.slf4j/slf4j-api/pom.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```
This should be fixed by the newest commit.

@rju  could you check the PR and either merge it or provide improvement suggestions?

**Review by rju — APPROVED** [review]

**Comment by rju** [comment]
The build on Jenkins does not work and fails with the message below.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signMavenJavaPublication'.
> Cannot perform signing task ':signMavenJavaPublication' because it has no configured signatory

**Review by rju — APPROVED** [review]

**Comment by rju** [comment]
The previous error is from the release-check-build. However, there was another error based on format issues. I fixed that.

**Comment by rju** [comment]
Now we have an issue in the Distribution step with: 

FAILURE: Build failed with an exception.

* What went wrong:
Task 'sign' is ambiguous in root project 'kieker'. Candidates are: 'signArchives', 'signMavenJavaPublication'.

**Pull request merged**
